name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
    - name: check files
      run: ls -a 
    
  download:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download text file
      uses: actions/download-artifact@v4
      with:
        name: hello.txt
        path: ./artifact
      
    - name: check files
      run: |
          ls -a 
      
    # - name: copy artifact
    #   run: cp hello.txt ./artifact
        
    - name: display content
      run: cat ./artifacts/hello.txt
